version: 2.1
orbs:
  cypress: cypress-io/cypress@1.26.0
workflows:
  build:
    jobs:
      - cypress/run:
          record: true
          start: 'npm start'
          wait-on: 'http://localhost:3000'
