/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'eu-west-1',
  aws_dynamodb_all_tables_region: 'eu-west-1',
  aws_dynamodb_table_schemas: [
    {
      tableName: 'articles-dev',
      region: 'eu-west-1'
    },
    {
      tableName: 'categories-dev',
      region: 'eu-west-1'
    }
  ],
  aws_cloud_logic_custom: [
    {
      name: 'apireactdeploy',
      endpoint: 'https://x15ez5s0bl.execute-api.eu-west-1.amazonaws.com/dev',
      region: 'eu-west-1'
    }
  ],
  aws_content_delivery_bucket: 'react-deploy-dev',
  aws_content_delivery_bucket_region: 'eu-west-1',
  aws_content_delivery_url: 'http://react-deploy-dev.s3-website-eu-west-1.amazonaws.com'
};

export default awsmobile;
